<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="7XITD-AZ39N" failures="2" tests="22" name="/Users/mlungisimbele/Documents/GitHub/waslah.web" time="270.699" errors="0" timestamp="2025-01-28T19:43:07 GMT+04:00">
  <testcase classname="tests.login_tests" name="loginSuccessfullyTest" time="2.991"/>
  <testcase classname="tests.login_tests" name="loginUnsuccessfullyTest1" time="1.472"/>
  <testcase classname="tests.login_tests" name="loginUnsuccessfullyTest2" time="2.285"/>
  <testcase classname="tests.login_tests" name="loginUnsuccessfullyTest3" time="2.367"/>
  <testcase classname="tests.login_tests" name="loginUnsuccessfullyTest4" time="1.066"/>
  <testcase classname="tests.login_tests" name="loginUnsuccessfullyTest5" time="1.189"/>
  <testcase classname="tests.login_tests" name="loginUnsuccessfullyTest6" time="0.78"/>
  <testcase classname="tests.login_tests" name="loginUnsuccessfullyTest7" time="1.163"/>
  <testcase classname="tests.login_tests" name="ResetPassword" time="1.452"/>
  <testcase classname="tests.login_tests" name="forgotPasswordSuccessfully" time="0.741"/>
  <testcase classname="tests.login_tests" name="InvalidEmail" time="0.588"/>
  <testcase classname="tests.login_tests" name="Logout" time="6.715"/>
  <testcase classname="tests.merchant_tests" name="CalculateCourierPriceAndSelectFedex" time="3.888">
    <failure type="java.lang.AssertionError" message="Courier selection could not be done for FedEx - test failed">
      <![CDATA[java.lang.AssertionError: Courier selection could not be done for FedEx - test failed
at org.testng.Assert.fail(Assert.java:110)
at teststeps.merchant_actions.SelectCourierFromCourierPage(merchant_actions.java:676)
at tests.merchant_tests.CalculateCourierPriceAndSelectFedex(merchant_tests.java:110)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- CalculateCourierPriceAndSelectFedex -->
  <testcase classname="tests.merchant_tests" name="CalculateCourierPricewithExceedingWeight" time="8.052"/>
  <testcase classname="tests.merchant_tests" name="CompleteWalletTopup" time="7.297"/>
  <testcase classname="tests.merchant_tests" name="POSRefundButton" time="10.373"/>
  <testcase classname="tests.merchant_tests" name="POSRefundButtonDisableCase1" time="7.012"/>
  <testcase classname="tests.merchant_tests" name="POSRefundButtonDisableCase2" time="9.322"/>
  <testcase classname="tests.merchant_tests" name="WalletMandatoryFieldTest" time="3.593">
    <failure type="java.lang.AssertionError" message="Wallet Mandatory field are blank - test failed">
      <![CDATA[java.lang.AssertionError: Wallet Mandatory field are blank - test failed
at org.testng.Assert.fail(Assert.java:110)
at teststeps.merchant_actions.WalletMandatoryFieldCheck(merchant_actions.java:786)
at tests.merchant_tests.WalletMandatoryFieldTest(merchant_tests.java:120)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- WalletMandatoryFieldTest -->
  <testcase classname="tests.merchant_tests" name="SignUpCompany" time="6.807"/>
  <testcase classname="tests.merchant_tests" name="SignUpIndividual" time="5.36"/>
  <testcase classname="tests.merchant_tests" name="CreateDomesticShipment" time="43.946"/>
</testsuite> <!-- /Users/mlungisimbele/Documents/GitHub/waslah.web -->
