<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="7XITD-AZ39N" failures="2" tests="10" name="tests.merchant_tests" time="167.774" errors="0" timestamp="2025-01-28T19:43:07 GMT+04:00" skipped="0">
  <testcase classname="tests.merchant_tests" name="WalletMandatoryFieldTest" time="9.230">
    <failure message="Wallet Mandatory field are blank - test failed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Wallet Mandatory field are blank - test failed
at org.testng.Assert.fail(Assert.java:110)
at teststeps.merchant_actions.WalletMandatoryFieldCheck(merchant_actions.java:786)
at tests.merchant_tests.WalletMandatoryFieldTest(merchant_tests.java:120)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- WalletMandatoryFieldTest -->
  <system-out/>
  <testcase classname="tests.merchant_tests" name="CompleteWalletTopup" time="12.990"/>
  <system-out/>
  <testcase classname="tests.merchant_tests" name="CalculateCourierPricewithExceedingWeight" time="13.774"/>
  <system-out/>
  <testcase classname="tests.merchant_tests" name="POSRefundButtonDisableCase1" time="13.238"/>
  <system-out/>
  <testcase classname="tests.merchant_tests" name="CalculateCourierPriceAndSelectFedex" time="9.582">
    <failure message="Courier selection could not be done for FedEx - test failed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Courier selection could not be done for FedEx - test failed
at org.testng.Assert.fail(Assert.java:110)
at teststeps.merchant_actions.SelectCourierFromCourierPage(merchant_actions.java:676)
at tests.merchant_tests.CalculateCourierPriceAndSelectFedex(merchant_tests.java:110)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- CalculateCourierPriceAndSelectFedex -->
  <system-out/>
  <testcase classname="tests.merchant_tests" name="POSRefundButtonDisableCase2" time="15.326"/>
  <system-out/>
  <testcase classname="tests.merchant_tests" name="POSRefundButton" time="15.983"/>
  <system-out/>
  <testcase classname="tests.merchant_tests" name="SignUpCompany" time="12.510"/>
  <system-out/>
  <testcase classname="tests.merchant_tests" name="SignUpIndividual" time="15.605"/>
  <system-out/>
  <testcase classname="tests.merchant_tests" name="CreateDomesticShipment" time="49.536"/>
  <system-out/>
</testsuite> <!-- tests.merchant_tests -->
